//! Sync session log helpers (E04-S06).
//!
//! Re-exports the storage types and provides high-level helpers for the
//! Push/Pull client and server to record session lifecycle events.
//!
//! ## Lifecycle
//! ```text
//!   begin_session()   →  status = Running
//!     │
//!     ├── success →  complete_session(objects, bytes)  →  status = Completed
//!     │
//!     └── failure →  fail_session(err)                →  status = Failed
//! ```
//!
//! Session ids are generated by the caller (BLAKE3 of a unique token / nanos).

pub use crate::store::traits::{
    SyncDirection, SyncSession, SyncSessionRepo, SyncSessionStatus,
};

use crate::error::CasResult;
use crate::model::current_timestamp;

/// Create a new in-progress sync session row.
///
/// Returns the inserted [`SyncSession`] (with `status = Running`,
/// `started_at = now`, all counters zero).
pub fn begin_session(
    repo: &dyn SyncSessionRepo,
    id: impl Into<String>,
    remote_name: impl Into<String>,
    direction: SyncDirection,
) -> CasResult<SyncSession> {
    let session = SyncSession {
        id: id.into(),
        remote_name: remote_name.into(),
        direction,
        status: SyncSessionStatus::Running,
        started_at: current_timestamp(),
        finished_at: None,
        objects_transferred: 0,
        bytes_transferred: 0,
        error_message: None,
    };
    repo.create_session(&session)?;
    Ok(session)
}

/// Mark a session as `Completed`, recording final transferred counts.
pub fn complete_session(
    repo: &dyn SyncSessionRepo,
    id: &str,
    objects_transferred: u64,
    bytes_transferred: u64,
) -> CasResult<SyncSession> {
    let mut session = repo
        .get_session(id)?
        .ok_or_else(|| crate::error::CasError::NotFound(format!("sync session {id}")))?;
    session.status = SyncSessionStatus::Completed;
    session.finished_at = Some(current_timestamp());
    session.objects_transferred = objects_transferred;
    session.bytes_transferred = bytes_transferred;
    session.error_message = None;
    repo.update_session(&session)?;
    Ok(session)
}

/// Mark a session as `Failed`, recording the error message.
pub fn fail_session(
    repo: &dyn SyncSessionRepo,
    id: &str,
    error: impl Into<String>,
) -> CasResult<SyncSession> {
    let mut session = repo
        .get_session(id)?
        .ok_or_else(|| crate::error::CasError::NotFound(format!("sync session {id}")))?;
    session.status = SyncSessionStatus::Failed;
    session.finished_at = Some(current_timestamp());
    session.error_message = Some(error.into());
    repo.update_session(&session)?;
    Ok(session)
}
